<a href="https://colab.research.google.com/github/AkankshaY05/FakeNewsClassifier/blob/main/FakeNewsClassifierUsingLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

fake = pd.read_csv("Fake.csv")
true = pd.read_csv("True.csv")

fake["label"] = 0   # fake news
true["label"] = 1   # real news

df = pd.concat([fake, true], axis=0)

In [ ]:
df = df.sample(frac=1, random_state=42)

In [ ]:
df["content"] = df["title"] + " " + df["text"]

X = df["content"]
y = df["label"]

In [ ]:
import pandas as pd

In [ ]:
#df=pd.read_csv('train.csv')

In [ ]:
df.head()

,title,text,subject,date,label,content
22216,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0,Ben Stein Calls Out 9th Circuit Court: Committ...
4436,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1,Trump drops Steve Bannon from National Securit...
1526,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1,Puerto Rico expects U.S. to lift Jones Act shi...
1377,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0,OOPS: Trump Just Accidentally Confirmed He Le...
8995,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1,Donald Trump heads for Scotland to reopen a go...


In [ ]:
df.shape

(44898, 6)

In [ ]:
df.head()

,title,text,subject,date,label,content
22216,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0,Ben Stein Calls Out 9th Circuit Court: Committ...
4436,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1,Trump drops Steve Bannon from National Securit...
1526,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1,Puerto Rico expects U.S. to lift Jones Act shi...
1377,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0,OOPS: Trump Just Accidentally Confirmed He Le...
8995,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1,Donald Trump heads for Scotland to reopen a go...


In [ ]:
df.isnull().sum()

,0
title,0
text,0
subject,0
date,0
label,0
content,0


In [ ]:
###Drop Nan Values
df=df.dropna()


In [ ]:
df.head()

,title,text,subject,date,label,content
22216,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0,Ben Stein Calls Out 9th Circuit Court: Committ...
4436,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1,Trump drops Steve Bannon from National Securit...
1526,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1,Puerto Rico expects U.S. to lift Jones Act shi...
1377,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0,OOPS: Trump Just Accidentally Confirmed He Le...
8995,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1,Donald Trump heads for Scotland to reopen a go...


In [ ]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [ ]:
## Get the Dependent features
y=df['label']

In [ ]:
X.shape

(44898, 5)

In [ ]:
y.shape

(44898,)

In [ ]:
import tensorflow as tf


In [ ]:
tf.__version__

'2.19.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages['title'][1]

,title
1,Drunk Bragging Trump Staffer Started Russian ...
1,U.S. military to accept transgender recruits o...


In [ ]:
messages

,title,text,subject,date,content
22216,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",Ben Stein Calls Out 9th Circuit Court: Committ...
4436,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",Trump drops Steve Bannon from National Securit...
1526,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",Puerto Rico expects U.S. to lift Jones Act shi...
1377,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",OOPS: Trump Just Accidentally Confirmed He Le...
8995,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",Donald Trump heads for Scotland to reopen a go...
...,...,...,...,...,...
11284,UNREAL! CBS’S TED KOPPEL Tells Sean Hannity He...,,politics,"Mar 27, 2017",UNREAL! CBS’S TED KOPPEL Tells Sean Hannity He...
21251,PM May seeks to ease Japan's Brexit fears duri...,LONDON/TOKYO (Reuters) - British Prime Ministe...,worldnews,"August 29, 2017",PM May seeks to ease Japan's Brexit fears duri...
14677,Merkel: Difficult German coalition talks can r...,BERLIN (Reuters) - Chancellor Angela Merkel sa...,worldnews,"November 16, 2017",Merkel: Difficult German coalition talks can r...
860,Trump Stole An Idea From North Korean Propaga...,Jesus f*cking Christ our President* is a moron...,News,"July 14, 2017",Trump Stole An Idea From North Korean Propaga...


In [ ]:
#messages.reset_index(inplace=True)

In [ ]:
messages

,title,text,subject,date,content
22216,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",Ben Stein Calls Out 9th Circuit Court: Committ...
4436,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",Trump drops Steve Bannon from National Securit...
1526,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",Puerto Rico expects U.S. to lift Jones Act shi...
1377,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",OOPS: Trump Just Accidentally Confirmed He Le...
8995,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",Donald Trump heads for Scotland to reopen a go...
...,...,...,...,...,...
11284,UNREAL! CBS’S TED KOPPEL Tells Sean Hannity He...,,politics,"Mar 27, 2017",UNREAL! CBS’S TED KOPPEL Tells Sean Hannity He...
21251,PM May seeks to ease Japan's Brexit fears duri...,LONDON/TOKYO (Reuters) - British Prime Ministe...,worldnews,"August 29, 2017",PM May seeks to ease Japan's Brexit fears duri...
14677,Merkel: Difficult German coalition talks can r...,BERLIN (Reuters) - Chancellor Angela Merkel sa...,worldnews,"November 16, 2017",Merkel: Difficult German coalition talks can r...
860,Trump Stole An Idea From North Korean Propaga...,Jesus f*cking Christ our President* is a moron...,News,"July 14, 2017",Trump Stole An Idea From North Korean Propaga...


In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', str(messages['title'].iloc[i]))
    #remove all the special char and replace it with blank
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['ben stein call th circuit court commit coup tat constitut',
 'trump drop steve bannon nation secur council',
 'puerto rico expect u lift jone act ship restrict',
 'oop trump accident confirm leak isra intellig russia video',
 'donald trump head scotland reopen golf resort',
 'paul ryan respond dem sit gun control disgust way video',
 'awesom diamond silk rip press believ video',
 'stand cheer ukip parti leader slam germani franc eu invas phoni refuge video',
 'north korea show sign seriou talk u offici',
 'trump signal willing rais u minimum wage',
 'new jersey christi mull run lead republican parti report',
 'hillari clinton spot dine alon',
 'franc germani want iran revers ballist missil program',
 'aid eu commiss head tweet pictur white smoke brexit meet may',
 'trump issu warn man armi could isi video',
 'u give lao extra million help clear unexplod ordnanc',
 'judg declar babi name illeg prevent emot harm',
 'paul ryan take monument humili photo constitu expertli troll imag',
 '

In [ ]:
corpus[1]

'trump drop steve bannon nation secur council'

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[959, 1344, 2433, 4251, 3414, 4251, 2649, 604, 369, 2297],
 [2304, 749, 3255, 1168, 3844, 2094, 3929],
 [3242, 658, 3422, 1446, 2969, 3575, 3578, 4393, 4038],
 [3164, 2304, 650, 4117, 4629, 801, 2152, 2798, 436],
 [4281, 2304, 2836, 782, 1133, 931, 4850],
 [4591, 3883, 1384, 638, 4313, 2534, 2723, 793, 51, 436],
 [644, 1174, 4070, 3327, 1677, 3879, 436],
 [1929, 4138, 4582, 4609, 4103, 3474, 2218, 4416, 2598, 759, 3640, 2305, 436],
 [2705, 286, 3050, 1555, 3412, 3885, 1446, 732],
 [2304, 4809, 3616, 2130, 1446, 188, 3300],
 [2503, 2966, 3049, 4070, 3912, 4560, 3649, 4609, 1093],
 [252, 3276, 3736, 3932, 323],
 [4416, 2218, 3850, 3990, 42, 3520, 4852, 391],
 [4970, 2598, 4176, 2836, 2014, 687, 4766, 1906, 1461, 4573, 3414],
 [2304, 1798, 2274, 3444, 4894, 95, 4539, 436],
 [1446, 2157, 2684, 1571, 3166, 2147, 4182, 4116, 1652],
 [2708, 364, 2562, 180, 2884, 4419, 3497, 172],
 [4591, 3883, 4009, 926, 28, 3554, 1102, 4292, 1979, 533],
 [3649, 3932, 2304, 1661, 2295, 63, 4182, 436],
 [1446

In [ ]:
corpus[1]

'trump drop steve bannon nation secur council'

In [ ]:
onehot_repr[1]

[2304, 749, 3255, 1168, 3844, 2094, 3929]

### Embedding Representation

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[ 959 1344 2433 ...    0    0    0]
 [2304  749 3255 ...    0    0    0]
 [3242  658 3422 ...    0    0    0]
 ...
 [2058 3738 3849 ...    0    0    0]
 [2304 2992 4482 ...    0    0    0]
 [1541  252 3276 ...    0    0    0]]


In [ ]:
embedded_docs[1]

array([2304,  749, 3255, 1168, 3844, 2094, 3929,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
embedded_docs[0]

array([ 959, 1344, 2433, 4251, 3414, 4251, 2649,  604,  369, 2297,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
## Creating model
from tensorflow.keras.layers import Input
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, embedding_vector_features))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
len(embedded_docs),y.shape

(44898, (44898,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((44898, 20), (44898,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.8993 - loss: 0.2352 - val_accuracy: 0.9395 - val_loss: 0.1570
Epoch 2/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9439 - loss: 0.1471 - val_accuracy: 0.9388 - val_loss: 0.1592
Epoch 3/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.9518 - loss: 0.1297 - val_accuracy: 0.9360 - val_loss: 0.1752
Epoch 4/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9545 - loss: 0.1215 - val_accuracy: 0.9344 - val_loss: 0.1592
Epoch 5/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.9586 - loss: 0.1109 - val_accuracy: 0.9372 - val_loss: 0.1668
Epoch 6/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9596 - loss: 0.1135 - val_accuracy: 0.9346 - val_loss: 0.1967
Epoch 7/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9626 - loss: 0.0985 - val_accuracy: 0.9368 - val_loss: 0.1797
Epoch 8/10
471/471 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.9661 - loss: 0.0874 - val_accuracy: 0.

### Adding Dropout

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


### Performance Metrics And Accuracy

In [ ]:
y_pred=model.predict(X_test)

464/464 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [ ]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[7350,  404],
       [ 561, 6502]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9348721063643113

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94      7754
           1       0.94      0.92      0.93      7063

    accuracy                           0.93     14817
   macro avg       0.94      0.93      0.93     14817
weighted avg       0.94      0.93      0.93     14817

